/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CipherSatisfaction {
  export type RatingStruct = {
    serviceAgentId: BytesLike;
    encryptedAttitude: BytesLike;
    encryptedSpeed: BytesLike;
    encryptedProfessionalism: BytesLike;
    encryptedWeightedScore: BytesLike;
    meetsThreshold: BytesLike;
    timestamp: BigNumberish;
  };

  export type RatingStructOutput = [
    serviceAgentId: string,
    encryptedAttitude: string,
    encryptedSpeed: string,
    encryptedProfessionalism: string,
    encryptedWeightedScore: string,
    meetsThreshold: string,
    timestamp: bigint
  ] & {
    serviceAgentId: string;
    encryptedAttitude: string;
    encryptedSpeed: string;
    encryptedProfessionalism: string;
    encryptedWeightedScore: string;
    meetsThreshold: string;
    timestamp: bigint;
  };

  export type StatisticsStruct = {
    totalRatings: BigNumberish;
    sumAttitude: BytesLike;
    sumSpeed: BytesLike;
    sumProfessionalism: BytesLike;
    sumWeightedScore: BytesLike;
    countMeetsThreshold: BytesLike;
  };

  export type StatisticsStructOutput = [
    totalRatings: bigint,
    sumAttitude: string,
    sumSpeed: string,
    sumProfessionalism: string,
    sumWeightedScore: string,
    countMeetsThreshold: string
  ] & {
    totalRatings: bigint;
    sumAttitude: string;
    sumSpeed: string;
    sumProfessionalism: string;
    sumWeightedScore: string;
    countMeetsThreshold: string;
  };
}

export interface CipherSatisfactionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admins"
      | "authorizeStatisticsDecryption"
      | "confidentialProtocolId"
      | "getAverages"
      | "getRating"
      | "getRatingCountForAgent"
      | "getStatistics"
      | "getTotalRatings"
      | "setAdmin"
      | "submitRating"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AdminUpdated" | "RatingSubmitted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "authorizeStatisticsDecryption",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAverages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRating",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRatingCountForAgent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRatings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRating",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeStatisticsDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAverages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRating", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRatingCountForAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRatings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRating",
    data: BytesLike
  ): Result;
}

export namespace AdminUpdatedEvent {
  export type InputTuple = [admin: AddressLike, isAdmin: boolean];
  export type OutputTuple = [admin: string, isAdmin: boolean];
  export interface OutputObject {
    admin: string;
    isAdmin: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingSubmittedEvent {
  export type InputTuple = [
    ratingId: BigNumberish,
    serviceAgentId: BytesLike,
    submitter: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    ratingId: bigint,
    serviceAgentId: string,
    submitter: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    ratingId: bigint;
    serviceAgentId: string;
    submitter: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CipherSatisfaction extends BaseContract {
  connect(runner?: ContractRunner | null): CipherSatisfaction;
  waitForDeployment(): Promise<this>;

  interface: CipherSatisfactionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  authorizeStatisticsDecryption: TypedContractMethod<[], [void], "nonpayable">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAverages: TypedContractMethod<
    [],
    [
      [string, string, string, string, string] & {
        averageAttitude: string;
        averageSpeed: string;
        averageProfessionalism: string;
        averageWeightedScore: string;
        thresholdPassRate: string;
      }
    ],
    "view"
  >;

  getRating: TypedContractMethod<
    [index: BigNumberish],
    [CipherSatisfaction.RatingStructOutput],
    "view"
  >;

  getRatingCountForAgent: TypedContractMethod<
    [serviceAgentId: BytesLike],
    [bigint],
    "view"
  >;

  getStatistics: TypedContractMethod<
    [],
    [CipherSatisfaction.StatisticsStructOutput],
    "view"
  >;

  getTotalRatings: TypedContractMethod<[], [bigint], "view">;

  setAdmin: TypedContractMethod<
    [admin: AddressLike, isAdmin: boolean],
    [void],
    "nonpayable"
  >;

  submitRating: TypedContractMethod<
    [
      serviceAgentId: BytesLike,
      encryptedAttitude: BytesLike,
      attitudeProof: BytesLike,
      encryptedSpeed: BytesLike,
      speedProof: BytesLike,
      encryptedProfessionalism: BytesLike,
      professionalismProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorizeStatisticsDecryption"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAverages"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, string] & {
        averageAttitude: string;
        averageSpeed: string;
        averageProfessionalism: string;
        averageWeightedScore: string;
        thresholdPassRate: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRating"
  ): TypedContractMethod<
    [index: BigNumberish],
    [CipherSatisfaction.RatingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRatingCountForAgent"
  ): TypedContractMethod<[serviceAgentId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStatistics"
  ): TypedContractMethod<
    [],
    [CipherSatisfaction.StatisticsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalRatings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<
    [admin: AddressLike, isAdmin: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitRating"
  ): TypedContractMethod<
    [
      serviceAgentId: BytesLike,
      encryptedAttitude: BytesLike,
      attitudeProof: BytesLike,
      encryptedSpeed: BytesLike,
      speedProof: BytesLike,
      encryptedProfessionalism: BytesLike,
      professionalismProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminUpdated"
  ): TypedContractEvent<
    AdminUpdatedEvent.InputTuple,
    AdminUpdatedEvent.OutputTuple,
    AdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RatingSubmitted"
  ): TypedContractEvent<
    RatingSubmittedEvent.InputTuple,
    RatingSubmittedEvent.OutputTuple,
    RatingSubmittedEvent.OutputObject
  >;

  filters: {
    "AdminUpdated(address,bool)": TypedContractEvent<
      AdminUpdatedEvent.InputTuple,
      AdminUpdatedEvent.OutputTuple,
      AdminUpdatedEvent.OutputObject
    >;
    AdminUpdated: TypedContractEvent<
      AdminUpdatedEvent.InputTuple,
      AdminUpdatedEvent.OutputTuple,
      AdminUpdatedEvent.OutputObject
    >;

    "RatingSubmitted(uint256,bytes32,address,uint256)": TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
    RatingSubmitted: TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
  };
}
